import type { Analysis } from "./types";

export function analysisToMarkdown(analysis: Analysis): string {
  const lines: string[] = [];

  const result = analysis.result;

  lines.push(`# Call Analysis: ${analysis.callId}`);
  lines.push("");
  lines.push(`**Date:** N/A`);
  lines.push(`**Gong Call ID:** N/A`);
  lines.push(`**Call ID:** ${result?.call_id || "N/A"}`);
  lines.push(`**Call Type:** ${result?.call_type || "N/A"}`);
  lines.push(`**Deal Stage:** ${result?.deal_stage || "N/A"}`);
  lines.push("");
  lines.push("**Participants:**");
  lines.push(`- Cast AI: ${result?.participants.cast_ai.join(", ") || "N/A"}`);
  lines.push(`- Customer: ${result?.participants.customer.join(", ") || "N/A"}`);
  lines.push("");

  if (!result) {
    lines.push("---");
    lines.push("*Generated by Gong Call Intelligence (Sales Call Assistant)*");
    return lines.join("\n");
  }

  lines.push("## Overall Summary");
  lines.push("");
  lines.push(result.overall_summary);
  lines.push("");

  lines.push("## Sentiment");
  lines.push("");
  lines.push("### Customer Sentiment");
  lines.push("");
  lines.push(`**Score:** ${result.sentiment.customer.score}`);
  lines.push(`**Rationale:** ${result.sentiment.customer.rationale}`);
  lines.push(`**Arc:** ${result.sentiment.customer.arc}`);
  lines.push("");
  if (result.sentiment.customer.key_moments.length > 0) {
    lines.push("**Key Moments:**");
    lines.push("");
    for (const moment of result.sentiment.customer.key_moments) {
      lines.push(`- ${moment.quote} (${moment.timestamp}) - ${moment.impact}`);
    }
    lines.push("");
  }
  if (result.sentiment.customer.unresolved_concerns.length > 0) {
    lines.push("**Unresolved Concerns:**");
    lines.push("");
    for (const concern of result.sentiment.customer.unresolved_concerns) {
      lines.push(`- ${concern}`);
    }
    lines.push("");
  }

  lines.push("### Cast AI Rep Sentiment");
  lines.push("");
  lines.push(`**Score:** ${result.sentiment.cast_ai_rep.score}`);
  lines.push(`**Rationale:** ${result.sentiment.cast_ai_rep.rationale}`);
  lines.push("");
  if (result.sentiment.cast_ai_rep.notes.length > 0) {
    lines.push("**Notes:**");
    lines.push("");
    for (const note of result.sentiment.cast_ai_rep.notes) {
      lines.push(`- ${note}`);
    }
    lines.push("");
  }

  lines.push("## Scorecard");
  lines.push("");
  lines.push("### Universal");
  lines.push("");
  if (result.scorecard.universal.length > 0) {
    lines.push("| Dimension | Score | Evidence | What Worked | What Didn't |");
    lines.push("|-----------|-------|----------|-------------|-------------|");
    for (const item of result.scorecard.universal) {
      const score = typeof item.score === "number" ? item.score : "N/A";
      lines.push(`| ${item.dimension} | ${score} | ${item.evidence} | ${item.what_worked} | ${item.what_didnt} |`);
    }
    lines.push("");
  } else {
    lines.push("No universal scorecard items.");
    lines.push("");
  }

  lines.push("### Call Type Specific");
  lines.push("");
  if (result.scorecard.call_type_specific.length > 0) {
    lines.push("| Dimension | Score | Evidence | What Worked | What Didn't |");
    lines.push("|-----------|-------|----------|-------------|-------------|");
    for (const item of result.scorecard.call_type_specific) {
      const score = typeof item.score === "number" ? item.score : "N/A";
      lines.push(`| ${item.dimension} | ${score} | ${item.evidence} | ${item.what_worked} | ${item.what_didnt} |`);
    }
    lines.push("");
  } else {
    lines.push("No call type specific scorecard items.");
    lines.push("");
  }

  lines.push("## Signal Flags");
  lines.push("");
  lines.push("### Competitor Mentions");
  if (result.signal_flags.competitor_mentions.present) {
    lines.push("");
    if (result.signal_flags.competitor_mentions.details.length > 0) {
      for (const detail of result.signal_flags.competitor_mentions.details) {
        lines.push(`- **${detail.competitor}**: ${detail.quote}`);
        lines.push(`  - Rep handling: ${detail.rep_handling}`);
      }
    } else {
      lines.push("");
      lines.push("Competitor mentions detected but no details available.");
    }
  } else {
    lines.push("");
    lines.push("No competitor mentions detected.");
  }
  lines.push("");

  lines.push("### Pricing Objections");
  if (result.signal_flags.pricing_objections.present) {
    lines.push("");
    if (result.signal_flags.pricing_objections.details.length > 0) {
      for (const detail of result.signal_flags.pricing_objections.details) {
        lines.push(`- ${detail.quote}`);
        lines.push(`  - Rep handling: ${detail.rep_handling}`);
      }
    } else {
      lines.push("");
      lines.push("Pricing objections detected but no details available.");
    }
  } else {
    lines.push("");
    lines.push("No pricing objections detected.");
  }
  lines.push("");

  lines.push("### Technical Objections");
  if (result.signal_flags.technical_objections.present) {
    lines.push("");
    if (result.signal_flags.technical_objections.details.length > 0) {
      for (const detail of result.signal_flags.technical_objections.details) {
        const resolved = detail.resolved ? "Resolved" : "Unresolved";
        lines.push(`- ${detail.quote} (${resolved})`);
        lines.push(`  - Rep handling: ${detail.rep_handling}`);
      }
    } else {
      lines.push("");
      lines.push("Technical objections detected but no details available.");
    }
  } else {
    lines.push("");
    lines.push("No technical objections detected.");
  }
  lines.push("");

  lines.push("### Champion/Blocker Dynamics");
  if (result.signal_flags.champion_blocker_dynamics.present) {
    lines.push("");
    if (result.signal_flags.champion_blocker_dynamics.details.length > 0) {
      for (const detail of result.signal_flags.champion_blocker_dynamics.details) {
        lines.push(`- **${detail.person}** (${detail.role})`);
        lines.push(`  - Evidence: ${detail.evidence}`);
      }
    } else {
      lines.push("");
      lines.push("Champion/blocker dynamics detected but no details available.");
    }
  } else {
    lines.push("");
    lines.push("No champion/blocker dynamics detected.");
  }
  lines.push("");

  lines.push("## What Went Well");
  lines.push("");
  if (result.what_went_well.length > 0) {
    for (let i = 0; i < result.what_went_well.length; i++) {
      const item = result.what_went_well[i];
      lines.push(`${i + 1}. **${item.title}**`);
      lines.push(`   - Transcript reference: ${item.transcript_reference}`);
      lines.push(`   - Why effective: ${item.why_effective}`);
      lines.push("");
    }
  } else {
    lines.push("No highlights of what went well.");
    lines.push("");
  }

  lines.push("## What Went Poorly");
  lines.push("");
  if (result.what_went_poorly.length > 0) {
    for (let i = 0; i < result.what_went_poorly.length; i++) {
      const item = result.what_went_poorly[i];
      lines.push(`${i + 1}. **${item.title}**`);
      lines.push(`   - Transcript reference: ${item.transcript_reference}`);
      lines.push(`   - Deal impact: ${item.deal_impact}`);
      lines.push("");
    }
  } else {
    lines.push("No highlights of what went poorly.");
    lines.push("");
  }

  lines.push("## Recommendations");
  lines.push("");
  lines.push("### Communication and Technique");
  lines.push("");
  if (result.recommendations.communication_and_technique.length > 0) {
    for (const rec of result.recommendations.communication_and_technique) {
      lines.push(`- ${rec}`);
    }
  } else {
    lines.push("No recommendations.");
  }
  lines.push("");

  lines.push("### Product Knowledge and Positioning");
  lines.push("");
  if (result.recommendations.product_knowledge_and_positioning.length > 0) {
    for (const rec of result.recommendations.product_knowledge_and_positioning) {
      lines.push(`- ${rec}`);
    }
  } else {
    lines.push("No recommendations.");
  }
  lines.push("");

  lines.push("### Process and Follow-through");
  lines.push("");
  if (result.recommendations.process_and_follow_through.length > 0) {
    for (const rec of result.recommendations.process_and_follow_through) {
      lines.push(`- ${rec}`);
    }
  } else {
    lines.push("No recommendations.");
  }
  lines.push("");

  lines.push("---");
  lines.push("*Generated by Gong Call Intelligence (Sales Call Assistant)*");

  return lines.join("\n");
}
